# Generated by Django 6.1 on 2026-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_custom_smtp',
            field=models.BooleanField(default=False),
        ),
    ]
