# Generated by Django 6.1 on 2026-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_customuser_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_tone_preference',
            field=models.CharField(default='professional', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groq_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='llm_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini 1.5'), ('openai', 'OpenAI GPT-4o'), ('claude', 'Anthropic Claude 3.5'), ('groq', 'Groq / Llama 3'), ('offline', 'Built-in Smart AI (Offline)')], default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
