# Generated by Django 6.1 on 2026-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_emailhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
