# Generated by Django 6.1 on 2026-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_alter_emailhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='bcc',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='folder',
            field=models.CharField(default='sent', max_length=50),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
